### ISSUE TITLE
Wrong title for example 4

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [fusion-energy/fusion_neutronics_workflow#20]
Example for is not a regular mesh tally example but an unstructured mesh

**Comment by shimwell** [comment]
It looks like it has some regular mesh tallies in to me

https://github.com/fusion-energy/fusion_neutronics_workflow/blob/015b72535a36f5e43e2504cddbc59a13488a3497/example_04_multi_volume_regular_mesh_tally/2_run_neutronics_simulation.py#L39-L47

**Comment by RemDelaporteMathurin** [comment]
Ah my bad I was maybe looking at an old branch...
