### ISSUE TITLE
Cadquery and Paramak not in docker image

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [fusion-energy/fusion_neutronics_workflow#31]
I pulled the latest docker image and it seems like cadquery isn't in it?

Did something go wrong with the build?

**Comment by shimwell** [comment]
The upload of artifacts at the end of the docker build failed
https://github.com/fusion-energy/fusion_neutronics_workflow/actions/runs/1844170413

however the docker image looks like it built and uploaded 

Also I can see cadquery install in the dockerfile
https://github.com/fusion-energy/fusion_neutronics_workflow/blob/84939c6fe1d0a681bd08a5d6356c9ba46c36355e/Dockerfile#L66

So I've made a PR to remove the upload step and can release a new dockerfile in a few hours once it has finished building

**Comment by RemDelaporteMathurin** [comment]
```python
#20 3.373 ERROR: Could not find a version that satisfies the requirement brep-to-h5m>=0.1.0 (from paramak==0.6.7->-r requirements.txt (line 2)) (from versions: none)
#20 3.373 ERROR: No matching distribution found for brep-to-h5m>=0.1.0 (from paramak==0.6.7->-r requirements.txt (line 2))
```

Is it something silly like `brep-to-h5m` instead of `brep_to_h5m`?

**Comment by RemDelaporteMathurin** [comment]
right I tried to recreate a new container, it worked. Nevermind
