### ISSUE TITLE
Perhaps add an image to the readme page

### ISSUE THREAD

**Issue by shimwell** [fusion-energy/fusion_neutronics_workflow#4]
![neutronics_workflow drawio](https://user-images.githubusercontent.com/8583900/135692965-b2200a96-0f3c-4410-a839-83d8e816b06a.png)

**Comment by Shimwell** [comment]
![neutronics_workflow drawio](https://user-images.githubusercontent.com/8583900/135693017-c86f5aa4-abb3-4cd8-96bf-82209e3e3be8.png)

**Comment by Shimwell** [comment]
fixed typos, thanks Remi

![neutronics_workflow drawio](https://user-images.githubusercontent.com/8583900/135835015-16a3ca70-1b50-4e3e-b266-333e8d6e18f3.png)

**Comment by shimwell** [comment]
![neutronics_workflow drawio(2)](https://user-images.githubusercontent.com/8583900/141475216-6876964f-0471-49ed-aa9d-b3000f2cb719.png)

**Comment by shimwell** [comment]
![neutronics_workflow drawio(2)](https://user-images.githubusercontent.com/8583900/141863141-9f04c63b-0fcb-4881-b7db-0d3001fd5fdc.png)

**Comment by shimwell** [comment]
![neutronics_workflow drawio(4)](https://user-images.githubusercontent.com/8583900/145485618-d4733a82-4f8a-4f8d-a669-7419f076a567.png)

**Comment by shimwell** [comment]
![neutronics_workflow drawio(5)](https://user-images.githubusercontent.com/8583900/150701623-29fbf50b-0203-4818-b318-2f3a996e1db7.png)
